// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: protos/vendor.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vendor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           int32  `protobuf:"varint,8,opt,name=ID,proto3" json:"ID,omitempty"`
	Name         string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email        string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	ContactNo    string `protobuf:"bytes,3,opt,name=ContactNo,proto3" json:"ContactNo,omitempty"`
	Website      string `protobuf:"bytes,4,opt,name=Website,proto3" json:"Website,omitempty"`
	Address      string `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	Status       string `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	LastModified int64  `protobuf:"varint,7,opt,name=LastModified,proto3" json:"LastModified,omitempty"`
}

func (x *Vendor) Reset() {
	*x = Vendor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vendor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendor) ProtoMessage() {}

func (x *Vendor) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vendor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendor.ProtoReflect.Descriptor instead.
func (*Vendor) Descriptor() ([]byte, []int) {
	return file_protos_vendor_proto_rawDescGZIP(), []int{0}
}

func (x *Vendor) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Vendor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vendor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Vendor) GetContactNo() string {
	if x != nil {
		return x.ContactNo
	}
	return ""
}

func (x *Vendor) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Vendor) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Vendor) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Vendor) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

type VendorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message   string  `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	VendorOut *Vendor `protobuf:"bytes,3,opt,name=VendorOut,proto3" json:"VendorOut,omitempty"`
}

func (x *VendorResponse) Reset() {
	*x = VendorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vendor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VendorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorResponse) ProtoMessage() {}

func (x *VendorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vendor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorResponse.ProtoReflect.Descriptor instead.
func (*VendorResponse) Descriptor() ([]byte, []int) {
	return file_protos_vendor_proto_rawDescGZIP(), []int{1}
}

func (x *VendorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VendorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VendorResponse) GetVendorOut() *Vendor {
	if x != nil {
		return x.VendorOut
	}
	return nil
}

var File_protos_vendor_proto protoreflect.FileDescriptor

var file_protos_vendor_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x22, 0xd0, 0x01,
	0x0a, 0x06, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4e, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4e, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c,
	0x4c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x22, 0x6c, 0x0a, 0x0e, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x2c, 0x0a, 0x09, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x4f, 0x75, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x2e, 0x56, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x52, 0x09, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x4f, 0x75, 0x74, 0x32, 0x40,
	0x0a, 0x0d, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x2f, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x0e, 0x2e, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x2e,
	0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x1a, 0x16, 0x2e, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x2e,
	0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x10, 0x5a, 0x0e, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_vendor_proto_rawDescOnce sync.Once
	file_protos_vendor_proto_rawDescData = file_protos_vendor_proto_rawDesc
)

func file_protos_vendor_proto_rawDescGZIP() []byte {
	file_protos_vendor_proto_rawDescOnce.Do(func() {
		file_protos_vendor_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_vendor_proto_rawDescData)
	})
	return file_protos_vendor_proto_rawDescData
}

var file_protos_vendor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_vendor_proto_goTypes = []interface{}{
	(*Vendor)(nil),         // 0: vendor.Vendor
	(*VendorResponse)(nil), // 1: vendor.VendorResponse
}
var file_protos_vendor_proto_depIdxs = []int32{
	0, // 0: vendor.VendorResponse.VendorOut:type_name -> vendor.Vendor
	0, // 1: vendor.VendorService.Add:input_type -> vendor.Vendor
	1, // 2: vendor.VendorService.Add:output_type -> vendor.VendorResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_vendor_proto_init() }
func file_protos_vendor_proto_init() {
	if File_protos_vendor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_vendor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vendor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vendor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VendorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_vendor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_vendor_proto_goTypes,
		DependencyIndexes: file_protos_vendor_proto_depIdxs,
		MessageInfos:      file_protos_vendor_proto_msgTypes,
	}.Build()
	File_protos_vendor_proto = out.File
	file_protos_vendor_proto_rawDesc = nil
	file_protos_vendor_proto_goTypes = nil
	file_protos_vendor_proto_depIdxs = nil
}
